### ISSUE TITLE
Migrage links on person_detection to use Harvard-CS249R-Fall2020

### ISSUE THREAD

**Issue by tclements** [Harvard-CS249R-Fall2020/assignments#1]
The links for the setup guide and assignement1 on the person_detection assignment page are pointing to 

https://github.com/tinyMLx/Harvard_CS249_F20/blob/master/assignments/person_detection/Setup.md

and

https://github.com/tinyMLx/Harvard_CS249_F20/tree/master/assignments/wake_words#deploying-a-speech-model-to-the-microcontroller-using-vscode--platformio

both of which lead to 404 not found errors. 

Should replace with 

https://github.com/Harvard-CS249R-Fall2020/assignments/blob/master/person_detection/Setup.md

and 

https://github.com/Harvard-CS249R-Fall2020/assignments/tree/master/wake_words#deploying-a-speech-model-to-the-microcontroller-using-vscode--platformio

**Comment by plancherb1** [comment]
Thanks updated to relative links so it won't break again if we move the repo location again!
